# ==================== Global ====================
global.width = 1280
global.height = 800
global.queue_size = 3

# ==================== BLC ====================
blc.r_offset = 20
blc.gr_offset = 20
blc.gb_offset = 20
blc.b_offset = 20
blc.async = false

# ==================== White balance ====================
wb.auto_wb = 0
wb.r_gain = 1.2
wb.g_gain = 1.0
wb.b_gain = 1.5
wb.async = false

# ==================== Demosaic ====================
demosaic.is_stereo = false
# 0~4: RGGB, GRBG, GBRG, BGGR
demosaic.base_bayer = 0
demosaic.rotate_180 = false
demosaic.rotate_r_180 = false
demosaic.async = true

# ==================== CCM + Gamma ====================
ccm_gamma.ccm.0 = 1.0
ccm_gamma.ccm.1 = 0.0
ccm_gamma.ccm.2 = 0.0
ccm_gamma.ccm.3 = 0.0
ccm_gamma.ccm.4 = 1.0
ccm_gamma.ccm.5 = 0.0
ccm_gamma.ccm.6 = 0.0
ccm_gamma.ccm.7 = 0.0
ccm_gamma.ccm.8 = 1.0
ccm_gamma.gamma = 2.2
ccm_gamma.async = true