// engine_depth.cpp — 方式B示例：调用 FaysSense SDK 深度引擎 (libfayssense_aikit_depth.so)
// 处理一张双目帧，输出深度图 / 校正图 / 点云。
//
// 用法: engine_depth <stacked.bmp> <stereo_depth.yaml> <out_prefix>
//   stacked.bmp       : 上下堆叠的双目帧 (上半 = 左相机, 下半 = 右相机), 灰度或 BGR
//   stereo_depth.yaml : SDK 深度配置文件 (见 config/stereo_depth.yaml)
//   out_prefix        : 输出文件前缀
//
// 输出:
//   <prefix>_depth.raw  float32 深度图 (米, 0=无效), 行优先 HxW
//   <prefix>_depth.png  伪彩深度图
//   <prefix>_rect.png   引擎校正后的双目图
//   <prefix>_pc.ply     引擎点云 (ASCII PLY)
//
// 注意:
//   - yaml 中的 model_path / calib_path 支持相对路径 (相对 yaml 所在目录), 引擎自行解析,
//     因此本包可从任意工作目录运行 (config/stereo_depth.yaml 已使用 ../ 相对路径)。
//   - 引擎 async_mode=1, 需要先喂若干帧"预热"管线, 之后 getDepthImage 才返回数据。
//   - 编译与链接依赖见 CMakeLists.txt / build.sh (x86_64 与 aarch64 均可)。
#include "depth_engine.h"
#include "colormap.h"

#include <opencv2/imgcodecs.hpp>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <unistd.h>
#include <vector>

// ---- ASCII PLY 输出 ----
static bool writePly(const std::string& path,
                     const std::vector<float>& xyz, const std::vector<uint8_t>& rgb)
{
    FILE* f = fopen(path.c_str(), "w");
    if (!f) return false;
    const size_t n = xyz.size() / 3;
    fprintf(f, "ply\nformat ascii 1.0\ncomment generated by engine_depth\n");
    fprintf(f, "element vertex %zu\n", n);
    fprintf(f, "property float x\nproperty float y\nproperty float z\n");
    fprintf(f, "property uchar red\nproperty uchar green\nproperty uchar blue\nend_header\n");
    for (size_t i = 0; i < n; ++i) {
        fprintf(f, "%.4f %.4f %.4f %u %u %u\n",
                xyz[3*i], xyz[3*i+1], xyz[3*i+2],
                rgb[3*i+2], rgb[3*i+1], rgb[3*i]);   // BGR -> RGB
    }
    fclose(f);
    return true;
}

int main(int argc, char** argv)
{
    if (argc < 4) {
        fprintf(stderr, "usage: %s <stacked.bmp> <stereo_depth.yaml> <out_prefix>\n", argv[0]);
        return 1;
    }

    cv::Mat stacked = cv::imread(argv[1], cv::IMREAD_COLOR);
    if (stacked.empty()) { fprintf(stderr, "cannot read %s\n", argv[1]); return 1; }

    std::string yamlPath = argv[2];

    DepthEngine eng(yamlPath);
    if (!eng.isInitialized()) {
        fprintf(stderr, "engine init failed (check model_path/calib_path and lib deps)\n");
        return 1;
    }

    // SGBM 参数 (与 GUI 默认一致), 仅 CPU 后端 (depth_mode: 1) 生效
    {
        const ATRAK_DepthParamKv kvs[] = {
            makeKv(ATRAK_DP_SGBM_MIN_DISP, 0),
            makeKv(ATRAK_DP_SGBM_NUM_DISP, 128),
            makeKv(ATRAK_DP_SGBM_WINDOW_SIZE, 11),
            makeKv(ATRAK_DP_SGBM_P1, 1904),
            makeKv(ATRAK_DP_SGBM_P2, 11616),
            makeKv(ATRAK_DP_SGBM_DISP12_MAX_DIFF, 4),
            makeKv(ATRAK_DP_SGBM_PRE_FILTER_CAP, 51),
            makeKv(ATRAK_DP_SGBM_UNIQUENESS_RATIO, 10),
            makeKv(ATRAK_DP_SGBM_SPECKLE_WINDOW_SIZE, 150),
            makeKv(ATRAK_DP_SGBM_SPECKLE_RANGE, 1),
            makeKv(ATRAK_DP_SGBM_MODE, 0),   // 0 = SGBM_3WAY
        };
        eng.setDepthParam(ATRAK_DEPTH_BACKEND_SGBM, kvs, 11);
    }

    // 预热: 引擎 async_mode=1, 需连续喂帧让管线跑起来
    for (int i = 0; i < 5; ++i) {
        eng.feedStereoImage(stacked, static_cast<uint64_t>(i) * 40000000ull);
        usleep(50000);
    }
    printf("[engine] warmed up with 5 frames\n");

    // 拉取深度 (带重试, 引擎前几帧可能还没有输出)
    cv::Mat depth, disp, paired;
    bool ok = false;
    for (int i = 0; i < 50 && !ok; ++i) {
        if (eng.getDepthImage(depth, disp, paired) && !depth.empty() && depth.cols > 0)
            ok = true;
        else
            usleep(100000);
    }
    if (!ok) { fprintf(stderr, "getDepthImage failed\n"); return 1; }
    printf("[depth] %dx%d float32 meters\n", depth.cols, depth.rows);

    const std::string pre = argv[3];

    // 1) float32 raw —— 外部程序读取的主接口
    {
        std::string raw = pre + "_depth.raw";
        FILE* f = fopen(raw.c_str(), "wb");
        fwrite(depth.data, 1, depth.total() * sizeof(float), f);
        fclose(f);
        printf("[out] %s (%dx%d float32, meters, 0=invalid)\n", raw.c_str(),
               depth.cols, depth.rows);
    }

    // 2) 伪彩 PNG
    cv::imwrite(pre + "_depth.png", applyDepthColormap(depth, 0.1f, 5.0f, true));

    // 3) 校正图
    {
        cv::Mat rect;
        if (eng.getRectifiedImage(rect) && !rect.empty()) {
            cv::imwrite(pre + "_rect.png", rect);
            printf("[out] %s_rect.png (%dx%d)\n", pre.c_str(), rect.cols, rect.rows);
        }
    }

    // 4) 点云
    {
        std::vector<float> xyz;
        std::vector<uint8_t> rgb;
        if (eng.getPointCloud(xyz, rgb, 262144) && !xyz.empty()) {
            writePly(pre + "_pc.ply", xyz, rgb);
            printf("[out] %s_pc.ply (%zu points)\n", pre.c_str(), xyz.size() / 3);
        }
    }

    // 统计
    {
        int valid = 0;
        double sum = 0;
        for (int y = 0; y < depth.rows; ++y) {
            const float* p = depth.ptr<float>(y);
            for (int x = 0; x < depth.cols; ++x)
                if (p[x] > 0) { ++valid; sum += p[x]; }
        }
        printf("[done] valid=%.1f%% mean=%.2fm\n",
               100.0 * valid / depth.total(), valid ? sum / valid : 0.0);
    }

    return 0;
}
