#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""read_depth.py — 读取 C++ 示例输出的 float32 深度图 (depth.raw)。

深度文件格式 (两种示例一致):
    float32 数组, 行优先 (row-major), 尺寸 H x W
    单位: 米 (meters)
    无效像素: 0.0

用法:
    python3 read_depth.py <depth.raw> <W> <H> [out.png] [out.ply]

示例:
    python3 read_depth.py out_depth.raw 1280 800 depth_view.png
    python3 read_depth.py out_depth.raw 1280 800 depth_view.png out_pc.ply

依赖: numpy (必须), opencv-python (可选, 用于伪彩 PNG 与点云 PLY)。
"""
import sys

import numpy as np


def load_depth_raw(path, w, h):
    """读取 raw 文件, 返回 (H, W) float32 深度图, 单位米, 0=无效。"""
    data = np.fromfile(path, dtype=np.float32)
    if data.size != w * h:
        raise ValueError(
            f"文件大小 {data.size} 与 WxH={w}x{h}={w*h} 不符, "
            f"请确认 W/H (深度图实际尺寸以示例打印的 [out] 行为准)"
        )
    return data.reshape(h, w)


def stats(depth):
    """有效像素占比 / 中位数 / 均值。"""
    valid = depth[depth > 0]
    total = depth.size
    print(f"shape      : {depth.shape[0]}x{depth.shape[1]}")
    print(f"valid      : {valid.size}/{total} = {100.0 * valid.size / total:.1f}%")
    if valid.size:
        print(f"median     : {np.median(valid):.3f} m")
        print(f"mean       : {valid.mean():.3f} m")
        print(f"range      : {valid.min():.3f} ~ {valid.max():.3f} m")
    # 每个像素的坐标 (右 x, 下 y), 便于外部程序换算
    ys, xs = np.nonzero(depth > 0)
    print(f"min valid  : x={xs.min()} y={ys.min()}, max valid: x={xs.max()} y={ys.max()}")


def save_colormap(depth, out_png):
    """用 cv2 生成伪彩图 (与 C++ 端 applyDepthColormap 同款色调)。"""
    import cv2

    depth = depth.astype(np.float32)
    norm = cv2.normalize(depth, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    color = cv2.applyColorMap(norm, cv2.COLORMAP_JET)
    color[depth <= 0] = (0, 0, 0)  # 无效像素置黑
    cv2.imwrite(out_png, color)
    print(f"[out] {out_png}")


def save_ply(depth, out_ply, fx=None, fy=None, cx=None, cy=None):
    """把深度图转成点云 (需要相机内参; 不传则输出像素坐标占位)。"""
    import cv2  # 仅用于读取不了原始图时说明

    h, w = depth.shape
    if fx is None:
        # 没有内参时, 输出 x=列, y=行, z=深度(米), 仅作数据结构示例
        ys, xs = np.nonzero(depth > 0)
        z = depth[ys, xs]
        xyz = np.stack([xs.astype(np.float32), ys.astype(np.float32), z], axis=1)
    else:
        ys, xs = np.nonzero(depth > 0)
        z = depth[ys, xs]
        xyz = np.stack([(xs - cx) / fx * z, (ys - cy) / fy * z, z], axis=1)

    with open(out_ply, "w") as f:
        f.write("ply\nformat ascii 1.0\ncomment generated by read_depth.py\n")
        f.write(f"element vertex {len(xyz)}\n")
        f.write("property float x\nproperty float y\nproperty float z\n")
        f.write("end_header\n")
        for p in xyz:
            f.write(f"{p[0]:.4f} {p[1]:.4f} {p[2]:.4f}\n")
    print(f"[out] {out_ply} ({len(xyz)} points)")


def main():
    if len(sys.argv) < 4:
        print(__doc__)
        return 1

    raw_path, w, h = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])
    depth = load_depth_raw(raw_path, w, h)
    stats(depth)

    if len(sys.argv) > 4:
        try:
            save_colormap(depth, sys.argv[4])
        except ImportError:
            print("提示: 未安装 opencv-python, 跳过伪彩图 (pip install opencv-python)")
    if len(sys.argv) > 5:
        try:
            save_ply(depth, sys.argv[5])
        except ImportError:
            print("提示: 未安装 opencv-python, 跳过点云输出")
    return 0


if __name__ == "__main__":
    sys.exit(main())
