// read_depth.cpp — 方式A示例：用 CPU 深度算法库处理一张双目帧，输出深度图。
//
// 用法: read_depth <stacked.bmp> <calib.yaml> <variant> <out_prefix>
//   stacked.bmp : 上下堆叠的双目帧 (上半 = 左相机, 下半 = 右相机)
//   calib.yaml  : kalibr 格式标定 (pinhole + equidistant/KB4)
//   variant     : 0=V1 针孔校正+SGBM   1=V2v 垂直极ERP+SGBM   2=V2b 基线极ERP+SGBM
//                 3=V3 多针孔分带(覆盖最大)  4=V4 针孔+BM(最快)
//   out_prefix  : 输出文件前缀
//
// 输出:
//   <prefix>_depth.raw  float32 深度图 (米, 0=无效), 行优先 HxW
//   <prefix>_depth.png  伪彩深度图
//   <prefix>_rect.png   校正后的双目图 (上=左, 下=右)
//   <prefix>_pc.ply     点云 (ASCII PLY)
//
// 依赖: OpenCV 4.x (系统自带即可), C++17
#include "cpu_depth.h"
#include "colormap.h"

#include <opencv2/imgcodecs.hpp>
#include <opencv2/calib3d.hpp>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

// ---- ASCII PLY 输出 (外部程序可直接用任意点云库读取) ----
static bool writePly(const std::string& path,
                     const std::vector<float>& xyz, const std::vector<uint8_t>& rgb)
{
    FILE* f = fopen(path.c_str(), "w");
    if (!f) return false;
    const size_t n = xyz.size() / 3;
    fprintf(f, "ply\nformat ascii 1.0\ncomment generated by read_depth\n");
    fprintf(f, "element vertex %zu\n", n);
    fprintf(f, "property float x\nproperty float y\nproperty float z\n");
    fprintf(f, "property uchar red\nproperty uchar green\nproperty uchar blue\nend_header\n");
    for (size_t i = 0; i < n; ++i) {
        fprintf(f, "%.4f %.4f %.4f %u %u %u\n",
                xyz[3*i], xyz[3*i+1], xyz[3*i+2],
                rgb[3*i+2], rgb[3*i+1], rgb[3*i]);   // BGR -> RGB
    }
    fclose(f);
    return true;
}

int main(int argc, char** argv)
{
    if (argc < 5) {
        fprintf(stderr, "usage: %s <stacked.bmp> <calib.yaml> <variant 0..4> <out_prefix>\n", argv[0]);
        return 1;
    }
    cv::Mat stacked = cv::imread(argv[1], cv::IMREAD_COLOR);
    if (stacked.empty()) { fprintf(stderr, "cannot read %s\n", argv[1]); return 1; }

    const int variant = atoi(argv[3]);
    if (variant < 0 || variant > cpu_depth::V4_PINHOLE_BM) {
        fprintf(stderr, "variant must be 0..4 (V5 needs the SDK engine, see engine_depth)\n");
        return 1;
    }

    cpu_depth::CpuDepthProcessor proc;
    if (!proc.loadCalib(argv[2])) { fprintf(stderr, "calib load failed: %s\n", argv[2]); return 1; }
    proc.setFrameSize(stacked.cols, stacked.rows / 2);

    cpu_depth::CpuOptions o;
    o.variant = variant;
    // 与 GUI 默认一致的 SGBM 参数, 可按需调整
    o.minDisp = 0; o.numDisp = 128; o.blockSize = 11;
    o.P1 = 1904; o.P2 = 11616; o.disp12MaxDiff = 4; o.preFilterCap = 51;
    o.uniquenessRatio = 10; o.speckleWindowSize = 150; o.speckleRange = 1;
    o.sgbmMode = cv::StereoSGBM::MODE_SGBM_3WAY;
    o.bandHalfDeg = 45.0; o.v3OutScale = 1.0; o.v3Relaxed = true;
    o.erpFillGap = 8.0; o.erpDensity = 4.0;
    proc.setOptions(o);

    cpu_depth::CpuResult res;
    if (!proc.process(stacked, nullptr, nullptr, 0.0, &res)) {
        fprintf(stderr, "process failed\n");
        return 1;
    }

    const std::string pre = argv[4];
    const char* names[] = {"v1", "v2v", "v2b", "v3", "v4"};

    // 1) float32 raw 深度 (米, 0=无效) —— 外部程序读取的主接口
    {
        std::string raw = pre + "_depth.raw";
        FILE* f = fopen(raw.c_str(), "wb");
        fwrite(res.depth.data, 1, res.depth.total() * sizeof(float), f);
        fclose(f);
        printf("[out] %s (%dx%d float32, meters, 0=invalid)\n", raw.c_str(),
               res.depth.cols, res.depth.rows);
    }

    // 2) 伪彩 PNG
    {
        cv::Mat color = applyDepthColormap(res.depth, 0.1f, 5.0f, true);
        cv::imwrite(pre + "_depth.png", color);
    }

    // 3) 校正双目 PNG
    if (!res.rectStereo.empty())
        cv::imwrite(pre + "_rect.png", res.rectStereo);

    // 4) 点云 PLY
    if (!res.pcXYZ.empty())
        writePly(pre + "_pc.ply", res.pcXYZ, res.pcRGB);

    printf("[done] %s: %dx%d valid=%.1f%% time=%.1fms\n", names[variant],
           res.depth.cols, res.depth.rows,
           100.0 * cv::countNonZero(res.depth > 0) / res.depth.total(),
           res.runtimeMs);
    return 0;
}
